version: '3'

services:
  app:
    build: .
    restart: on-failure
    ports:
      - "80:5000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:15.1-alpine3.17
    volumes:
      - ./pg_db:/var/lib/postgresql/data/
    expose:
      - "5432"
    ports:
      - "5432:5432"
    env_file:
      - .env
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    depends_on:
      - db
    environment:
      - .env
